### ISSUE TITLE
Check metadata

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-209aPlaintiffMotionToModify#66]
```
metadata:
  title: |
    209A Plaintiff's Motion to Modify an Abuse Prevention Order
  short title: |
    209A Plaintiff's Motion to Modify
  description: |
    If the plaintiff already has a restraining order, they can ask the court to change or end it.
```

**Comment by CaroRob** [comment]
Yep, 1st screen should say, "Ask the court to change or end your 209A restraining order"

**Comment by plocket** [comment]
Great, I'll change the 1st screen text. I'm asking about the metadata text shown above, though. Does that need to change too, or should that stay as it is - more accurate to the actual motion.

**Comment by plocket** [comment]
Kate said it doesn't matter one way or the other, so I'm opting for plain language in the `metadata`.
