### ISSUE TITLE
id: basic questions intro screen - should not be promising user they email form to the court.

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-209aPlaintiffMotionToModify#69]
Need to fix instruction about emailing motion to court? 
@kateleebarry 
What are we doing about these opening screens whilst we do not know how Pro Se peeps are getting files to court? 

 The MassAccess Project can help **Massachusetts residents** complete and file court forms in 3 steps:

Step 1. Answer questions that will fill in your form for you.
Step 2. Preview the completed form.
_Step 3. Email the form to the court using this secure website and save copies for yourself for later reference._ Need to fix this, not sure where we are in Assembly Line production with this question

Maybe we should adapt the opening screen in the 209A interview? Need to think about this I think.

**Comment by kateleebarry** [comment]
How about: 
Step 3. Download the form and call the court to find out the best way to file it.
