### ISSUE TITLE
id: motion to modify intro - need to fill in info for defendant who is in the wrong place

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-209aPlaintiffMotionToModify#70]
What do we want to tell defendants who cannot use this interview at the beginning of the order?
See 

- [What if the person who abused me files a protective order or criminal case against me?](https://www.masslegalhelp.org/domestic-violence/abuser-takes-me-to-court)
- [Massachusetts law about defending against a c.209A Order](https://www.mass.gov/lists/restraining-orderabuse-prevention-order-court-forms)?
- [Restraining Orders - Mental Health Legal Advisors Committee](http://mhlac.org/wp-content/uploads/2018/10/restraining_order.pdf#page=3)?
- Talk to a lawyer?

**Comment by kateleebarry** [comment]
Can we just refer them to this form on Mass.gov: https://www.mass.gov/doc/defendants-motion-to-modify-or-terminate-abuse-prevention-order-gl-c-209a/download

**Comment by plocket** [comment]
☝️ Would that link alone work, @CaroRob ?

**Comment by plocket** [comment]
Conclusion: Defendants in these situations really need a lawyer. Advise defendant to talk to a lawyer and provide a link to https://masslrf.org/en/home.
