### ISSUE TITLE
id: signature choice

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-209aPlaintiffMotionToModify#71]
This may be part of the big package, but unless we have a question at the beginning for an advocate to help a plaintiff, it is confusing to have the option to email the form to someone else to sign. 

I already said I am the plaintiff at the beginning of the interview - why would I send this form to anyone else to sign?

**Comment by plocket** [comment]
I wonder if there's some kind of wording that could be more ambiguous but still work. Maybe like 'send the form to be signed on another device'?

**Comment by kateleebarry** [comment]
I think Michelle's suggestion is good.  I like having the option of emailing just in case.

**Comment by plocket** [comment]
To clarify my meaning, you might not send it to be signed by someone else, but you might send it to yourself on a different device.

**Comment by plocket** [comment]
The current problem with that wording is that it's passive voice. I'm not sure how to improve it. Do you have suggestions, @CaroRob?

**Comment by plocket** [comment]
Created issue upstream: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/91
